package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.freeDiskSpace
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildFeatures.swabra
import jetbrains.buildServer.configs.kotlin.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
    }
    steps {
        insert(0) {
            maven {
                name = "Deploy relese"

                conditions {
                    equals("teamcity.build.branch.is_default", "true")
                }
                goals = "clean deploy"
                userSettingsSelection = "maven"
                localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
            }
        }
        insert(1) {
            maven {
                name = "test not relese branch"

                conditions {
                    doesNotEqual("teamcity.build.branch", "master")
                }
                goals = "clean test"
                runnerArgs = "-Dmaven.test.failure.ignore=true"
                userSettingsSelection = "maven"
                localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
            }
        }
    }

    features {
        add {
            swabra {
            }
        }
        add {
            freeDiskSpace {
                failBuild = true
            }
        }
        add {
            perfmon {
            }
        }
    }
}
